# Generated by Django 5.2.14 on 2026-05-09 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='must_change_password',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='temporary_password_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
