# Generated by Django 5.2.14 on 2026-05-13 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_must_change_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPERADMIN', 'Super Admin'), ('MANAGER', 'Manager'), ('CASHIER', 'Cashier'), ('INVENTORY', 'Inventory')], default='CASHIER', max_length=20),
        ),
    ]
