# Generated by Django 5.2.14 on 2026-05-13 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_menu'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['status', 'is_active'], name='products_pr_status_c4a457_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['menu', 'name'], name='products_pr_menu_id_c1abeb_idx'),
        ),
    ]
