# Generated by Django 5.2.14 on 2026-05-13 05:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('products', '0003_product_products_pr_status_c4a457_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='stockitem',
            index=models.Index(fields=['quantity', 'low_stock_threshold'], name='inventory_s_quantit_66742e_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['product', 'created_at'], name='inventory_s_product_5919a9_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['movement_type', 'created_at'], name='inventory_s_movemen_ed5291_idx'),
        ),
    ]
