# Generated by Django 5.2.14 on 2026-05-11 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('TRANSFER', 'Transfer'), ('CARD', 'Card'), ('MIXED', 'Mixed')], default='CASH', max_length=20),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='product_name_snapshot',
            field=models.CharField(default='Unknown Product', max_length=255),
            preserve_default=False,
        ),
    ]
