# Generated by Django 5.2.14 on 2026-05-13 05:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_products_pr_status_c4a457_idx_and_more'),
        ('sales', '0002_sale_payment_method_saleitem_product_name_snapshot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='payment_status',
            field=models.CharField(choices=[('PAID', 'Paid'), ('PARTIAL', 'Partial'), ('UNPAID', 'Unpaid')], default='UNPAID', max_length=20),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['payment_status', 'created_at'], name='sales_sale_payment_45d06e_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['cashier', 'created_at'], name='sales_sale_cashier_9d4ec1_idx'),
        ),
        migrations.AddIndex(
            model_name='saleitem',
            index=models.Index(fields=['sale', 'product'], name='sales_salei_sale_id_17278e_idx'),
        ),
        migrations.AddIndex(
            model_name='saleitem',
            index=models.Index(fields=['product_name_snapshot'], name='sales_salei_product_74ff80_idx'),
        ),
    ]
