# Generated by Django 5.2.14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_alter_sale_payment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='receipt_printed',
            field=models.BooleanField(default=False),
        ),
    ]