# Generated by Django 5.2.14 on 2026-05-11 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('TRANSFER', 'Transfer'), ('CARD', 'Card'), ('MIXED', 'Mixed')], max_length=20),
        ),
    ]
