# Generated by Django 5.2.14 on 2026-05-13 05:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_alter_payment_payment_method'),
        ('sales', '0003_alter_sale_payment_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['created_at', 'payment_method'], name='payment_pay_created_31dfa1_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['sale', 'created_at'], name='payment_pay_sale_id_0577d5_idx'),
        ),
    ]
