# Generated by Django 5.2.14 on 2026-06-01 10:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_payment_payment_pay_created_31dfa1_idx_and_more'),
        ('sales', '0003_alter_sale_payment_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('INITIAL', 'Initial payment'), ('REPAYMENT', 'Repayment')], default='INITIAL', max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='sequence_number',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['sale', 'payment_type', 'sequence_number'], name='payment_pay_sale_id_1011a9_idx'),
        ),
    ]
